version: 0.0
os: linux
files:
  - source: /application
    destination: /home/ubuntu/express
hooks:
  BeforeInstall:
    - location: ./scripts/install-dependencies.sh
      timeout: 150
      runas: root
  ApplicationStart:
    - location: ./scripts/start-service.sh
      timeout: 150
      runas: root
  ValidateService:
    - location: ./scripts/validate-service.sh
      timeout: 150
      runas: root